<!DOCTYPE html>
<html lang="<?= $this->lang ?>">
<head>
    <meta charset="UTF-8">
    <base href="www.ajezek.cz"/>

    <script src="/js/jQuery.min.js"></script>

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-101006784-1', 'auto');
        ga('send', 'pageview');

    </script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="/css/font-awesome.css"/>
    <link rel="stylesheet" type="text/css" href="/css/FontAwesome/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="/css/style.css">

    <script src="/js/smooth-scroll.js"></script>


    <title><?= $title ?></title>
</head>
<body>


<nav class="menu" id="menu">
    <div class="menu__wrapper">
        <h1 class="menu__nadpis"><a class="menu__nadpis--a" href="/home#home">Adam Ježek</a></h1>
        <button id="tlacitko-telefon" class="menu__TelefonTlacitko"><i class="fa fa-bars"></i></button>
        <div class="menu__pc-telefon--overeni"></div>
        <div class="menu__telefon">
            <ul class="menu__ul menu__hlavniMenu">
                <li class="menu__polozka"><a class="menu__odkaz"
                                             href="/<?= $this->lang ?>/home#home"> <?= $labels["about"] ?> </a></li>
                <li class="menu__polozka"><a class="menu__odkaz"
                                             href="/<?= $this->lang ?>/home#abilities"><?= $labels["abilities"] ?> </a>
                </li>
                <li class="menu__polozka"><a class="menu__odkaz"
                                             href="/<?= $this->lang ?>/home#reference"><?= $labels["references"] ?> </a>
                </li>
                <li class="menu__polozka"><a class="menu__odkaz"
                                             href="/<?= $this->lang ?>/home#kontakty"><?= $labels["contacts"] ?> </a>
                </li>

            </ul>

            <?php
            $ln = "cs";
            $lntx = "CZ";
            if ($this->lang == "cs") {
                $ln = "en";
                $lntx = "ENG";
            }
            ?>
            <a href="https://ajezek.cz/<?= $ln ?>" class="menu__odkaz  menu__polozka"
               style="float:right"><img src="/icon/<?= $ln ?>_flag.png" width="32px"/></a>

            <div class="menu__polozka" style="float: right;"><a href="https://twitter.com/adamjezek98"
                                                                class="menu__polozka" target="_blank"> <i
                            class="fa fa-twitter twitter-icon" aria-hidden="true"></i></a></div>

        </div>
    </div>
</nav>
<script type="text/javascript" src="/js/menu.js"></script>

<article>
    <div style="height: 1px;"></div>
    <?php $this->controller->printView();  // vložení aktuálního pohledu do šablony ?>
    <div style="clear: both;"></div>
</article>

<footer>
    <div style="padding-right: 20px;"> &copy; Adam Ježek 2017, mail@ajezek.cz, responzive menu by
        SogoCZE
    </div>
</footer>
</body>
</html>